const populateIcons = async () => {
  try {
    // Define icon data to be inserted
    const iconData = [
      {
          name: "Grinning Face", 
          thumbnail: "/images/thumbnails/Grinning-Face.png",
          svg: "/images/svg/Grinning-Face.svg",
          type: "free",
          tags: ["Grinning", "Smiling", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Grinning Face with Big Eyes", 
          thumbnail: "/images/thumbnails/Grinning-Face-with-Big-Eyes.png",
          svg: "/images/svg/Grinning-Face-with-Big-Eyes.svg",
          type: "free",
          tags: ["Grinning", "Smiling", "Face", "Emoji", "Big Eyes"],
          price: 0.00
        },
        { name: "Grinning Face with Smiling Eyes", 
          thumbnail: "/images/thumbnails/Grinning-Face-with-Smiling-Eyes.png",
          svg: "/images/svg/Grinning-Face-with-Smiling-Eyes.svg",
          type: "free",
          tags: ["Grinning", "Smiling", "Face", "Emoji", "Smiling   Eyes"],
          price: 0.00
        },
        { name: "Beaming Face with Smiling Eyes", 
          thumbnail: "/images/thumbnails/Beaming-Face-with-Smiling-Eyes.png",
          svg: "/images/svg/Beaming-Face-with-Smiling-Eyes.svg",
          type: "free",
          tags: ["Beaming", "Smiling", "Face", "Emoji", "Smiling   Eyes"],
          price: 0.00
        },
        { name: "Grinning Squinting Face", 
          thumbnail: "/images/thumbnails/Grinning-Squinting-Face.png",
          svg: "/images/svg/Grinning-Squinting-Face.svg",
          type: "free",
          tags: ["Grinning", "Squinting", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Rolling on the Floor Laughing", 
          thumbnail: "/images/thumbnails/Rolling-on-the-Floor-Laughing.png",
          svg: "/images/svg/Rolling-on-the-Floor-Laughing.svg",
          type: "free",
          tags: ["Rolling", "Laughing", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Grinning Face with Sweat", 
          thumbnail: "/images/thumbnails/Grinning-Face-with-Sweat.png",
          svg: "/images/svg/Grinning-Face-with-Sweat.svg",
          type: "free",
          tags: ["Grinning", "Sweat", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Slightly Smiling Face", 
          thumbnail: "/images/thumbnails/Slightly-Smiling-Face.png",
          svg: "/images/svg/Slightly-Smiling-Face.svg",
          type: "free",
          tags: ["Smiling", "Slightly Smiling", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Face with Tears of Joy", 
          thumbnail: "/images/thumbnails/Face-with-Tears-of-Joy.png",
          svg: "/images/svg/Face-with-Tears-of-Joy.svg",
          type: "free",
          tags: ["Tears of Joy", "Joy", "Laughing", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Upside-Down Face", 
          thumbnail: "/images/thumbnails/Upside-Down-Face.png",
          svg: "/images/svg/Upside-Down-Face.svg",
          type: "free",
          tags: ["Upside-Down", "Smiling", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Winking Face", 
          thumbnail: "/images/thumbnails/Winking-Face.png",
          svg: "/images/svg/Winking-Face.svg",
          type: "free",
          tags: ["Winking", "Smiling", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Smiling Face with Halo", 
          thumbnail: "/images/thumbnails/Smiling-Face-with-Halo.png",
          svg: "/images/svg/Smiling-Face-with-Halo.svg",
          type: "free",
          tags: ["Smiling", "Halo", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Smiling Face with Hearts", 
          thumbnail: "/images/thumbnails/Smiling-Face-with-Hearts.png",
          svg: "/images/svg/Smiling-Face-with-Hearts.svg",
          type: "premium",
          tags: ["Smiling", "Hearts", "Face", "Emoji"],
          price: 6.25
        },
        { name: "Smiling Face with Heart-Eyes", 
          thumbnail: "/images/thumbnails/Smiling-Face-with-Heart-Eyes.png",
          svg: "/images/svg/Smiling-Face-with-Heart-Eyes.svg",
          type: "free",
          tags: ["Smiling", "Hearts", "Heart-Eyes", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Face Blowing a Kiss", 
          thumbnail: "/images/thumbnails/Face-Blowing-a-Kiss.png",
          svg: "/images/svg/Face-Blowing-a-Kiss.svg",
          type: "free",
          tags: ["Smiling", "Blowing a Kiss", "Kissing", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Kissing Face with Closed Eyes", 
          thumbnail: "/images/thumbnails/Kissing-Face-with-Closed-Eyes.png",
          svg: "/images/svg/Kissing-Face-with-Closed-Eyes.svg",
          type: "free",
          tags: ["Smiling", "Kissing", "Closed Eyes", "Face", "Emoji"],
          price: 0.00 
        },
        { name: "Kissing Face", 
          thumbnail: "/images/thumbnails/Kissing-Face.png",
          svg: "/images/svg/Kissing-Face.svg",
          type: "free",
          tags: ["Smiling", "Kissing", "Face", "Emoji"],
          price: 0.00 
        },
        { name: "Kissing Face with Smiling Eyes", 
          thumbnail: "/images/thumbnails/Kissing-Face-with-Smiling-Eyes.png",
          svg: "/images/svg/Kissing-Face-with-Smiling-Eyes.svg",
          type: "free",
          tags: ["Smiling", "Kissing", "Smiling Eyes", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Star-Struck", 
          thumbnail: "/images/thumbnails/Star-Struck.png",
          svg: "/images/svg/Star-Struck.svg",
          type: "premium",
          tags: ["Smiling", "Star-Struck", "Star Eyes", "Face", "Emoji"],
          price: 2.40
        },
        { name: "Smiling Face", 
          thumbnail: "/images/thumbnails/Smiling-Face.png",
          svg: "/images/svg/Smiling-Face.svg",
          type: "free",
          tags: ["Smiling", "Face", "Emoji"],
          price: 0.00 
        },
        { name: "Smiling Face with Tear", 
          thumbnail: "/images/thumbnails/Smiling-Face-with-Tear.png",
          svg: "/images/svg/Smiling-Face-with-Tear.svg",
          type: "free",
          tags: ["Smiling", "Tears", "Face", "Emoji"],
          price: 0.00  
        },
        { name: "Face Savoring Food", 
          thumbnail: "/images/thumbnails/Face-Savoring-Food.png",
          svg: "/images/svg/Face-Savoring-Food.svg",
          type: "free",
          tags: ["Savoring Food", "Tongue Out", "Face", "Emoji"],
          price: 0.00  
        },
        { name: "Face with Tongue", 
          thumbnail: "/images/thumbnails/Face-with-Tongue.png",
          svg: "/images/svg/Face-with-Tongue.svg",
          type: "free",
          tags: ["Tongue Out", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Winking Face with Tongue", 
          thumbnail: "/images/thumbnails/Winking-Face-with-Tongue.png",
          svg: "/images/svg/Winking-Face-with-Tongue.svg",
          type: "free",
          tags: ["Winking", "Tongue Out", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Zany Face with Tongue", 
          thumbnail: "/images/thumbnails/Zany-Face-with-Tongue.png",
          svg: "/images/svg/Zany-Face-with-Tongue.svg",
          type: "free",
          tags: ["Zany", "Tongue", "Happy", "Rolling Eyes", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Squinting Face with Tongue", 
          thumbnail: "/images/thumbnails/Squinting-Face-with-Tongue.png",
          svg: "/images/svg/Squinting-Face-with-Tongue.svg",
          type: "free",
          tags: ["Squinting", "Tongue", "Happy", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Money-Mouth Face", 
          thumbnail: "/images/thumbnails/Money-Mouth-Face.png",
          svg: "/images/svg/Money-Mouth-Face.svg",
          type: "free",
          tags: ["Money Mouth", "Rich", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Face with Raised Eyebrow", 
          thumbnail: "/images/thumbnails/Face-with-Raised-Eyebrow.png",
          svg: "/images/svg/Face-with-Raised-Eyebrow.svg",
          type: "free",
          tags: ["Raised Eyebrow", "Angry", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Neutral Face", 
          thumbnail: "/images/thumbnails/Neutral-Face.png",
          svg: "/images/svg/Neutral-Face.svg",
          type: "free",
          tags: ["Neutral", "Expressionless", "Speachless", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Expressionless Face", 
          thumbnail: "/images/thumbnails/Expressionless-Face.png",
          svg: "/images/svg/Expressionless-Face.svg",
          type: "free",
          tags: ["Expressionless", "Neutral", "Speachless", "Face", "Emoji"],
          price: 0.00 
        },
        { name: "Face Without Mouth", 
          thumbnail: "/images/thumbnails/Face-Without-Mouth.png",
          svg: "/images/svg/Face-Without-Mouth.svg",
          type: "free" ,
          tags: ["Without Mouth", "Speachless", "Face", "Emoji"],
          price: 0.00 
        },
        { name: "Dotted Line Face", 
          thumbnail: "/images/thumbnails/Dotted-Line-Face.png",
          svg: "/images/svg/Dotted-Line-Face.svg",
          type: "free",
          tags: ["Dotted Line", "Angry", "Face", "Emoji"],
          price: 0.00 
        },
        { name: "Smirking Face", 
          thumbnail: "/images/thumbnails/Smirking-Face.png",
          svg: "/images/svg/Smirking-Face.svg",
          type: "free",
          tags: ["Smirking", "Face", "Emoji"],
          price: 0.00 
        },
        { name: "Unamused Face", 
          thumbnail: "/images/thumbnails/Unamused-Face.png",
          svg: "/images/svg/Unamused-Face.svg",
          type: "free",
          tags: ["Unamused", "Angry", "Face", "Emoji"],
          price: 0.00 
        },
        { name: "Face with Rolling Eyes", 
          thumbnail: "/images/thumbnails/Face-with-Rolling-Eyes.png",
          svg: "/images/svg/Face-with-Rolling-Eyes.svg",
          type: "premium",
          tags: ["Rolling Eyes", "Angry", "Face", "Emoji"],
          price: 8.43 
        },
        { name: "Grimacing Face", 
          thumbnail: "/images/thumbnails/Grimacing-Face.png",
          svg: "/images/svg/Grimacing-Face.svg",
          type: "free",
          tags: ["Grimacing", "Face", "Emoji"],
          price: 0.00 
        },
        { name: "Face Exhaling", 
          thumbnail: "/images/thumbnails/Face-Exhaling.png",
          svg: "/images/svg/Face-Exhaling.svg",
          type: "free",
          tags: ["Exhaling", "Relieved", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Lying Face", 
          thumbnail: "/images/thumbnails/Lying-Face.png",
          svg: "/images/svg/Lying-Face.svg",
          type: "free",
          tags: ["Lying", "Nose", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Relieved Face", 
          thumbnail: "/images/thumbnails/Relieved-Face.png" ,
          svg: "/images/svg/Relieved-Face.svg",
          type: "free",
          tags: ["Relieved", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Pensive Face", 
          thumbnail: "/images/thumbnails/Pensive-Face.png",
          svg: "/images/svg/Pensive-Face.svg",
          type: "free",
          tags: ["Pensive", "Sad", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Sleepy Face", 
          thumbnail: "/images/thumbnails/Sleepy-Face.png",
          svg: "/images/svg/Sleepy-Face.svg",
          type: "free",
          tags: ["Sleepy", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Drooling Face", 
          thumbnail: "/images/thumbnails/Drooling-Face.png",
          svg: "/images/svg/Drooling-Face.svg",
          type: "free",
          tags: ["Drooling", "Hungry", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Sleeping Face", 
          thumbnail: "/images/thumbnails/Sleeping-Face.png",
          svg: "/images/svg/Sleeping-Face.svg",
          type: "free",
          tags: ["Sleeping", "Face", "Emoji"],
          price: 0.00 
        },
        { name: "Face with Medical Mask", 
          thumbnail: "/images/thumbnails/Face-with-Medical-Mask.png",
          svg: "/images/svg/Face-with-Medical-Mask.svg",
          type: "free",
          tags: ["Medical Mask", "Corona", "Face", "Emoji"],
          price: 0.00 
        },
        { name: "Nauseated Face", 
          thumbnail: "/images/thumbnails/Nauseated-Face.png",
          svg: "/images/svg/Nauseated-Face.svg",
          type: "free",
          tags: ["Nauseated", "Face", "Emoji"],
          price: 0.00 
        },
        { name: "Woozy Face", 
          thumbnail: "/images/thumbnails/Woozy-Face.png",
          svg: "/images/svg/Woozy-Face.svg",
          type: "premium",
          tags: ["Woozy", "Face", "Emoji"],
          price: 8.43
        },
        { name: "Face with Crossed-Out Eyes", 
          thumbnail: "/images/thumbnails/Face-with-Crossed-Out-Eyes.png",
          svg: "/images/svg/Face-with-Crossed-Out-Eyes.svg",
          type: "free",
          tags: ["Crossed-Out Eyes", "Surprised", "Face", "Emoji"],
          price: 0.00 
        },
        { name: "Smiling Face with Sunglasses", 
          thumbnail: "/images/thumbnails/Smiling-Face-with-Sunglasses.png",
          svg: "/images/svg/Smiling-Face-with-Sunglasses.svg",
          type: "free",
          tags: ["Smiling", "Sunglasses", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Face with Monocle", 
          thumbnail: "/images/thumbnails/Face-with-Monocle.png",
          svg: "/images/svg/Face-with-Monocle.svg",
          type: "free",
          tags: ["Monocle", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Confused Face", 
          thumbnail: "/images/thumbnails/Confused-Face.png",
          svg: "/images/svg/Confused-Face.svg",
          type: "free",
          tags: ["Confused", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Face with Diagonal Mouth", 
          thumbnail: "/images/thumbnails/Face-with-Diagonal-Mouth.png",
          svg: "/images/svg/Face-with-Diagonal-Mouth.svg",
          type: "free",
          tags: ["Diagonal Mouth", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Worried Face", 
          thumbnail: "/images/thumbnails/Worried-Face.png",
          svg: "/images/svg/Worried-Face.svg",
          type: "free",
          tags: ["Worried", "Sad", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Slightly Frowning Face", 
          thumbnail: "/images/thumbnails/Slightly-Frowning-Face.png",
          svg: "/images/svg/Slightly-Frowning-Face.svg",
          type: "free",
          tags: ["Slightly Frowning", "Sad", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Frowning Face", 
          thumbnail: "/images/thumbnails/Frowning-Face.png",
          svg: "/images/svg/Frowning-Face.svg",
          type: "free",
          tags: ["Frowning", "Sad", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Face with Open Mouth", 
          thumbnail: "/images/thumbnails/Face-with-Open-Mouth.png",
          svg: "/images/svg/Face-with-Open-Mouth.svg",
          type: "free",
          tags: ["Hushed", "Astonished", "Surprised", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Hushed Face", 
          thumbnail: "/images/thumbnails/Hushed-Face.png",
          svg: "/images/svg/Hushed-Face.svg",
          type: "free",
          tags: ["Hushed", "Astonished", "Surprised", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Astonished Face", 
          thumbnail: "/images/thumbnails/Astonished-Face.png",
          svg: "/images/svg/Astonished-Face.svg",
          type: "free",
          tags: ["Astonished", "Surprised", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Flushed Face", 
          thumbnail: "/images/thumbnails/Flushed-Face.png",
          svg: "/images/svg/Flushed-Face.svg",
          type: "free",
          tags: ["Flushed", "Surprised", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Pleading Face", 
          thumbnail: "/images/thumbnails/Pleading-Face.png",
          svg: "/images/svg/Pleading-Face.svg",
          type: "free",
          tags: ["Pleading", "Sad", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Face Holding Back Tears", 
          thumbnail: "/images/thumbnails/Face-Holding-Back-Tears.png",
          svg: "/images/svg/Face-Holding-Back-Tears.svg",
          type: "premium",
          tags: ["Holding Back Tears", "Sad", "Tears", "Face", "Emoji"],
          price: 9.63
        },
        { name: "Frowning Face with Open Mouth", 
          thumbnail: "/images/thumbnails/Frowning-Face-with-Open-Mouth.png",
          svg: "/images/svg/Frowning-Face-with-Open-Mouth.svg",
          type: "free",
          tags: ["Frowning", "Anxious", "sad", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Anguished Face", 
          thumbnail: "/images/thumbnails/Anguished-Face.png",
          svg: "/images/svg/Anguished-Face.svg",
          type: "free",
          tags: ["Anguished", "Anxious", "sad", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Anxious Face with Sweat", 
          thumbnail: "/images/thumbnails/Anxious-Face-with-Sweat.png",
          svg: "/images/svg/Anxious-Face-with-Sweat.svg",
          type: "free",
          tags: ["Anxious", "Sweat", "sad", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Sad but Relieved Face", 
          thumbnail: "/images/thumbnails/Sad-but-Relieved-Face.png",
          svg: "/images/svg/Sad-but-Relieved-Face.svg",
          type: "free",
          tags: ["Relieved", "sad", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Crying Face", 
          thumbnail: "/images/thumbnails/Crying-Face.png",
          svg: "/images/svg/Crying-Face.svg",
          type: "free",
          tags: ["Crying", "sad", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Loudly Crying Face", 
          thumbnail: "/images/thumbnails/Loudly-Crying-Face.png",
          svg: "/images/svg/Loudly-Crying-Face.svg",
          type: "free",
          tags: ["Loudly Crying", "sad", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Confounded Face", 
          thumbnail: "/images/thumbnails/Confounded-Face.png",
          svg: "/images/svg/Confounded-Face.svg",
          type: "free",
          tags: ["Confounded Face", "sad", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Persevering Face", 
          thumbnail: "/images/thumbnails/Persevering-Face.png",
          svg: "/images/svg/Persevering-Face.svg",
          type: "free",
          tags: ["Persevering Face", "sad", "Face", "Emoji"],
          price: 0.00 
        },
        { name: "Disappointed Face", 
          thumbnail: "/images/thumbnails/Disappointed-Face.png",
          svg: "/images/svg/Disappointed-Face.svg",
          type: "free",
          tags: ["Disappointed Face", "sad", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Downcast Face with Sweat", 
          thumbnail: "/images/thumbnails/Downcast-Face-with-Sweat.png",
          svg: "/images/svg/Downcast-Face-with-Sweat.svg",
          type: "free",
          tags: ["Downcast Face", "Sweat", "sad", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Weary Face", 
          thumbnail: "/images/thumbnails/Weary-Face.png",
          svg: "/images/svg/Weary-Face.svg",
          type: "free",
          tags: ["Weary Face", "Weary", "sad", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Tired Face", 
          thumbnail: "/images/thumbnails/Tired-Face.png",
          svg: "/images/svg/Tired-Face.svg",
          type: "premium",
          tags: ["Tired Face", "Tired", "Face", "Emoji"],
          price: 2.40
        },
        { name: "Angry Face", 
          thumbnail: "/images/thumbnails/Angry-Face.png",
          svg: "/images/svg/Angry-Face.svg",
          type: "free",
          tags: ["Angry Face", "Angry", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Face with Symbols on Mouth", 
          thumbnail: "/images/thumbnails/Face-with-Symbols-on-Mouth.png",
          svg: "/images/svg/Face-with-Symbols-on-Mouth.svg",
          type: "free",
          tags: ["Symbols on Mouth", "Angry", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Smiling Face with Horns", 
          thumbnail: "/images/thumbnails/Smiling-Face-with-Horns.png",
          svg: "/images/svg/Smiling-Face-with-Horns.svg",
          type: "free",
          tags: ["Smiling Face", "Horns", "Face", "Emoji"],
          price: 0.00
        },
        { name: "Angry Face with Horns", 
          thumbnail: "/images/thumbnails/Angry-Face-with-Horns.png",
          svg: "/images/svg/Angry-Face-with-Horns.svg",
          type: "free",
          tags: ["Angry Face", "Horns", "Face", "Emoji"],
          price: 0.00
        }
    ];
    await IconModel.insertMany(iconData);

    console.log("Icons populated successfully!");
  } catch (error) {
    console.error("Error populating icons:", error);
  }
};