import Head from 'next/head';
import HomePage from '../src/components/HomePage';

export default function Home({initialIcons, iconsCount}) {
  return (
    <div>
      <Head>
        <title>Icons App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage data={initialIcons} iconsCount={iconsCount} />
    </div>
  )
}

export const getStaticProps = async () => {
  try {
    const res = await fetch('http://localhost:3000/api/icons?page=1');
    const data = await res.json();

    if (!data || !data.icons || !data.iconsCount) {
      throw new Error('Failed to fetch icons data');
    }
    
    return {
      props: {
        initialIcons: data.icons
      },
  };
  } catch (error) {
    console.log('Error fetching icons data:', error);
    return {
      props: {
        initialIcons: []
      },
    };
  } 
}

